In [7]:
import sys
sys.path.append('..')

import torch
import torch.nn as nn

In [18]:
m = nn.ConstantPad1d(2, 3.5)
input = torch.randn(1, 2, 4)

In [22]:
input.shape

torch.Size([1, 2, 4])

In [23]:
input

tensor([[[ 0.1611, -1.0728, -1.1125,  0.6358],
         [ 0.8735, -0.0426,  0.1344, -1.2180]]])

In [24]:
m(input).shape

torch.Size([1, 2, 8])

In [25]:
m(input)

tensor([[[ 3.5000,  3.5000,  0.1611, -1.0728, -1.1125,  0.6358,  3.5000,
           3.5000],
         [ 3.5000,  3.5000,  0.8735, -0.0426,  0.1344, -1.2180,  3.5000,
           3.5000]]])

In [26]:
m = nn.ConstantPad1d(2, 3.5)
input = torch.rand(1, 2, 3)

In [27]:
input

tensor([[[0.9594, 0.5669, 0.3933],
         [0.6299, 0.0850, 0.8742]]])

In [29]:
m(input)

tensor([[[3.5000, 3.5000, 0.9594, 0.5669, 0.3933, 3.5000, 3.5000],
         [3.5000, 3.5000, 0.6299, 0.0850, 0.8742, 3.5000, 3.5000]]])

In [37]:
m = nn.ConstantPad1d((3, 1), 3.5)
m(input)

tensor([[[3.5000, 3.5000, 3.5000, 0.9594, 0.5669, 0.3933, 3.5000],
         [3.5000, 3.5000, 3.5000, 0.6299, 0.0850, 0.8742, 3.5000]]])